# ADHD200 data
# #     for a large number of participants for group-level analyses

- anat: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-1019436/ses-1/anat/sub-1019436_ses-1_run-1_T1w.nii.gz
  func:
    rest_acq-1_run-1:
      scan: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-1019436/ses-1/func/sub-1019436_ses-1_task-rest_acq-1_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/task-rest_acq-1_bold.json
  site: KKI
  subject_id: '1019436'
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-2014113/ses-1/anat/sub-2014113_ses-1_run-1_T1w.nii.gz
  func:
    rest_acq-2_run-1:
      scan: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-2014113/ses-1/func/sub-2014113_ses-1_task-rest_acq-2_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/task-rest_acq-2_bold.json
  site: KKI
  subject_id: '2014113'
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-3154996/ses-1/anat/sub-3154996_ses-1_run-1_T1w.nii.gz
  func:
    rest_acq-2_run-1:
      scan: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/sub-3154996/ses-1/func/sub-3154996_ses-1_task-rest_acq-2_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI/task-rest_acq-2_bold.json
  site: KKI
  subject_id: '3154996'
  unique_id: '1'

# NKI-Rockland Sample NFB3 data
#     for field maps
- anat: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/anat/sub-A00028185_ses-NFB3_T1w.nii.gz
  func:
    MORALDILEMMA:
      fmap_mag: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_magnitude1.nii.gz
      fmap_phase: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_phasediff.nii.gz
      scan: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/func/sub-A00028185_ses-NFB3_task-MORALDILEMMA_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/task-MORALDILEMMA_bold.json
    MSIT:
      fmap_mag: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_magnitude1.nii.gz
      fmap_phase: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_phasediff.nii.gz
      scan: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/func/sub-A00028185_ses-NFB3_task-MSIT_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/task-MSIT_bold.json
  site: NKI
  subject_id: A00028185
  unique_id: NFB3
- anat: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/anat/sub-A00028352_ses-NFB3_T1w.nii.gz
  func:
    MORALDILEMMA:
      fmap_mag: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/fmap/sub-A00028352_ses-NFB3_magnitude1.nii.gz
      fmap_phase: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/fmap/sub-A00028352_ses-NFB3_phasediff.nii.gz
      scan: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/func/sub-A00028352_ses-NFB3_task-MORALDILEMMA_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/task-MORALDILEMMA_bold.json
    MSIT:
      fmap_mag: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/fmap/sub-A00028352_ses-NFB3_magnitude1.nii.gz
      fmap_phase: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/fmap/sub-A00028352_ses-NFB3_phasediff.nii.gz
      scan: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028352/ses-NFB3/func/sub-A00028352_ses-NFB3_task-MSIT_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/task-MSIT_bold.json
  site: NKI
  subject_id: A00028352
  unique_id: NFB3
