%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# # Version 1.8.3
# #
# # http://fcp-indi.github.io for more info.
# #
# # Tip: This file can be edited manually with a text editor for quick modifications.
#

FROM: rodent

pipeline_setup:
  system_config:
    random_seed: 2022
