settings:
  n_cpus: 16
  correlations_dir: /media/ebs/CPAC_regtest_pack/new_run_scripts/correlations
  run_name: 'v183-vs-v184_abcd-options_fixed-2022'
  s3_creds:
  quick: False
  verbose: True

pipelines:
  v183_abcd-options_fixed-2022:
    output_dir: /media/ebs/runs/v183_abcd-options-fixedseed-2022/output/cpac_cpac_abcd-options 
    work_dir: /media/ebs/runs/v181_abcd-options/working
    log_dir: /media/ebs/runs/v181_abcd-options/working/log
    pipe_config: /media/ebs/runs/v181_abcd-options/cpac_pipeline_config_2022-05-07T22-51-16Z.yml
    replacements:
  v184_abcd-options_fixed-2022:
    output_dir: /media/ebs/runs/v184_abcd-options/output/cpac_cpac_abcd-options
    work_dir: /media/ebs/runs/v184_abcd-options/working
    log_dir: /media/ebs/runs/v184_abcd-options/working/log
    pipe_config: /media/ebs/runs/v184_abcd-options/cpac_pipeline_config_2022-05-07T06-37-31Z.yml
    replacements:
